FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
RUN apk upgrade --no-cache && apk add --no-cache ca-certificates git \
    && git config --system --add safe.directory '*' \
    && git config --system user.name FerrFlow \
    && git config --system user.email bot@ferrflow.com \
    && adduser -D -u 1000 ferrflow
ARG TARGETARCH
COPY ferrflow-${TARGETARCH} /usr/local/bin/ferrflow
USER ferrflow
WORKDIR /repo
ENTRYPOINT ["ferrflow"]
CMD ["--help"]
