name: Renovate rebase now

on:
  pull_request:
    types: [edited]

jobs:
  dispatch:
    uses: FerrLabs/.github/.github/workflows/reusable-renovate-dispatch.yml@84b33d7a9df1bc988686b28e7a298ca88990b653 # main
    with:
      runner: ubuntu-latest
    secrets: inherit
